name: Convert

on:
  push:
    branches:
      - main
#    paths:
#      - mappings/**

jobs:
  convert-mappings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install yaml-to-table
      run: |
        python -m pip install --upgrade pip
        pip install git+git://github.com/ishswar/yaml-to-table.git@master
    - name: Convert Series-TVDB-English from YAML to Table
      run: python yaml_to_table.py --inputFile 'mappings/series-tvdb.en.yaml' --out html
