name: Convert

on:
  push:
    branches:
      - main
#    paths:
#      - mappings/**
jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: abc
        with:
          path: 'mappings/abc.yaml'
          from: 'yaml'
          to: 'xml'
      - name: Print series-tvdb-en-xml result
        run: echo "${{ steps.abc.outputs.data }}"
